akun/urls.py
from django.contrib import admin
from django.urls import path
from akun.views import index

app_name = "akun"

urlpatterns = [
    path('', index, name='akun'),
]

book/urls.py
from django.contrib import admin
from django.urls import path
from book.views import index, find_book

app_name = "book"

urlpatterns = [ 
    path('', index, name='index'),
    path('find_book/<str:q>', find_book),
]

home/urls.py
from django.contrib import admin
from django.urls import path
from home.views import landing

app_name = "home"

urlpatterns = [ 
    path('', landing, name='land'),
]

status/urls.py
from django.contrib import admin
from django.urls import path
from status.views import index

app_name = "status"

urlpatterns = [
    path('', index, name='home'),
]

tdd/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('status.urls')),
    path('home/', include('home.urls')),
    path('book/', include('book.urls')),
    path('akun/', include('akun.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

akun/models.py
from django.db import models

# Create your models here.

book/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

status/models.py
from django.db import models
from django.utils import timezone

class Status(models.Model):
    status = models.TextField(max_length = 300)
    time_created = models.DateTimeField(default = timezone.now)

status/forms.py
from django import forms
from status.models import Status

class StatusForm(forms.ModelForm):
    status = forms.CharField(widget=forms.Textarea(
        attrs = {
            'type' : 'text',
            'id'   : 'status',
                }
    ))

    class Meta:
        model = Status
        fields = "__all__"
        exclude = (
            "time_created",
        )

akun/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'akun/akun.html')

book/views.py
from django.shortcuts import render
from django.http.response import JsonResponse

import requests

def index(request):
    return render (request, "book.html")

def find_book(request, q):
    response = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + q)
    books = response.json()
    return JsonResponse(books)

home/views.py
from django.shortcuts import render, redirect

def landing (request):
    return render(request, 'home.html')

status/views.py
from django.shortcuts import render
from status.forms import StatusForm
from status.models import Status

def index(request):
    form = StatusForm(request.POST or None)
    data = Status.objects.all()
    context = {
        'status' : data,
        'form'  : form,
    }
    if request.method == "POST" and form.is_valid():
        form.save()
    return render(request, 'status.html', context)

akun/templates/akun/akun.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'book/style.css' %}">
    <title>Welcome</title>
</head>
<body>
    <div class="center">
        <h1>Home</h1>
        {% if user.is_authenticated %}
            <span>Hello {{ user.username }}, what would you do?</span><br>
            <a href="{% url 'logout' %}">Log out</a>
        {% else %}
            <span>Welcome to my website, not login yet?</span><br>
            <a href="{% url 'login' %}">Login</a>
        {% endif %}
    </div>
</body>
</html>

book/templates/book.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'book/style.css' %}">
    <script src="{% static 'book/index.js' %}"></script>
    <title>Search Books</title>
</head>
<body>
    <div class="search-text">
        <span class="center-text"><b>Search your books here!</b><br></span>
        <span class="center"><input id="search-book" type="search" placeholder="Search here"></span>
        <span class="center"><button type="button" id="search">Search</button></span>
        
    </div>
    <div id="result-table">
        <div id="found-book" class="center"></div>
        <table class="table table-striped table-dark">         
            <thead>
                <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Thumbnail</th>
                    <th scope="col">Authors</th>   
                    <th scope="col">Description</th>
                </tr>
            </thead>
            <tbody id="result-body">
            </tbody>
        </table> 
    </div>
    
</body>
</html>

home/templates/home.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'home/style.css' %}">
        <script src="{% static 'home/style.js' %}"></script>
        <title>Home</title>
    </head>
    <body class="light">
        <header>
            <nav class="navbar navbar-light bg-light fixed-top" id="navbar-bootstrap">
                <a class="navbar-brand">Home</a>
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="customSwitch1">
                    <label class="custom-control-label" for="customSwitch1">Ganti Tema</label>
                </div>
            </nav>
        </header>
        <div class="home-center">
            Selamat Datang! <br>menggunakan tema
            <div id="home-desc-tema">
                TERANG
            </div>
            <div class="home-accordion">
                <button class="accordion">Aktivitas saat ini</button>
                <div class="panel">
                    <p>Semester 3 Fasilkom UI</p>
                </div>

                <button class="accordion">Pengalaman</button>
                <div class="panel">
                    <p>PPW, SDA, Matdas 2</p>
                </div>

                <button class="accordion">Prestasi</button>
                <div class="panel">
                    <p>Coming soon</p>
                </div>
            </div>
            
        </div>     

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

status/templates/status.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'status/style.css' %}">
    <title>What's Up?</title>
</head>
<body>
    <div class="tbl">
        <div class="center">
            Halo, apa kabar?
        </div>
        <div class="center">
           <form action="{% url 'status:home' %}" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Kirim" id="submit-status">
        </form> 
        </div>
        
    </div>   
    <div>
        <table class="table table-striped table-dark">         
            <thead>
            <tr>
                <th scope="col">Status</th>
                <th scope="col">Tanggal Pembuatan</th>
            </tr>
            </thead>
            <tbody>
                {% for kata in status %}
                    {% if not status %}
                        <div class="text-center">Belum ada status</div>
                    {% else %}                          
                    <tr>
                        <td>{{kata.status}}</td>
                        <td>{{kata.time_created}}</td>
                    </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>   
    </div> 
</body>
</html>